ekf_node:
  ros__parameters:
    process_noise_vx: 0.1
    process_noise_vy: 0.01 # wheel odometry trust
    process_noise_yaw: 0.5 # wheel odometry for yaw trust
    imu_heading_noise: 0.05 # imu for yaw trust
